import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Payal One",
    author: "Pritam Kumar",
    currentPrice: 3999,
    categoryName: "Payal",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/payal1_kkkhac.jpg",
    description: "This is Payal.",
    rating: 4,
    inStock: 0,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Payal Two",
    author: "Pritam Kumar",
    currentPrice: 4000,
    categoryName: "Payal",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/payal5_jymczh.jpg",
    description: "This is Payal.",
    rating: 4,
    inStock: 3,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Payal Three",
    author: "Pritam Kumar",
    currentPrice: 9000,
    categoryName: "Payal",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/payal3_pr8t83.jpg",
    description: "This is Payal.",
    rating: 4,
    inStock: 15,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Payal Four",
    author: "Pritam Kumar",
    currentPrice: 4000,
    categoryName: "Payal",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/payal4_ulbgaq.jpg",
    description: "This is Payal.",
    rating: 4,
    inStock: 12,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Payal Five",
    author: "Pritam Kumar",
    currentPrice: 5600,
    categoryName: "Payal",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/payal2_tcb3aq.jpg",
    description: "This is Payal.",
    rating: 4,
    inStock: 0,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Ring One",
    author: "Pritam Kumar",
    currentPrice: 2000,
    categoryName: "Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168586/ring1_jw683f.png",
    description: "This is Ring",
    rating: 3,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Ring Two",
    author: "Pritam Kumar",
    currentPrice: 66000,
    categoryName: "Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168586/ring2_oydetp.png",
    description: "This is Ring",
    rating: 3,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Ring Three",
    author: "Pritam Kumar",
    currentPrice: 22000,
    categoryName: "Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168586/ring3_xetzsm.png",
    description: "This is Ring",
    rating: 3,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Ring Four",
    author: "Pritam Kumar",
    currentPrice: 57700,
    categoryName: "Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168586/ring4_v0mzoq.png",
    description: "This is Ring",
    rating: 3,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Ring Five",
    author: "Pritam Kumar",
    currentPrice: 59900,
    categoryName: "Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168586/ring5_xyo4wh.png",
    description: "This is Ring",
    rating: 2,
    inStock: 0,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Ear Ring One",
    author: "Pritam Kumar",
    currentPrice: 5000,
    categoryName: "Ear Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168583/earring1_h43srb.png",
    description: "This is Ear Ring",
    rating: 2,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Ear Ring Two",
    author: "Pritam Kumar",
    currentPrice: 5000,
    categoryName: "Ear Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168583/earring2_gqjcbq.png",
    description: "This is Ear Ring",
    rating: 2,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Ear Ring Three",
    author: "Pritam Kumar",
    currentPrice: 5000,
    categoryName: "Ear Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168583/earring3_fyjmgr.png",
    description: "This is Ear Ring",
    rating: 2,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Ear Ring Four",
    author: "Pritam Kumar",
  currentPrice: 500,
    categoryName: "Ear Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168583/earring4_qjfski.png",
    description: "This is Ear Ring",
    rating: 2,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Ear Ring Five",
    author: "Pritam Kumar",
    currentPrice: 58800,
    categoryName: "Ear Ring",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168583/earring5_g2vwle.png",
    description: "This is Ear Ring",
    rating: 1,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Necklace One",
    author: "Pritam Kumar",
    currentPrice: 3400,
    categoryName: "Necklace",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168584/necklace1_nv0gxu.png",
    description: "This is Necklace.",
    rating: 1,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Necklace Two",
    author: "Pritam Kumar",
    currentPrice: 23000,
    categoryName: "Necklace",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168585/necklace2_aups97.png",
    description: "This is Necklace.",
    rating: 1,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
    featured: true
  },
  {
    _id: uuid(),
    title: "Necklace Three",
    author: "Pritam Kumar",
    currentPrice: 7000,
    categoryName: "Necklace",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168584/necklace3_taj2zs.png",
    description: "This is Necklace.",
    rating: 1,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Necklace Four",
    author: "Pritam Kumar",
    currentPrice: 9600,
    categoryName: "Necklace",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168584/necklace4_gsxaxb.png",
    description: "This is Necklace.",
    rating: 3,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  },
  {
    _id: uuid(),
    title: "Necklace Five",
    author: "Pritam Kumar",
    currentPrice: 34000,
    categoryName: "Necklace",
    image: "https://res.cloudinary.com/dhqxln7zi/image/upload/v1647168584/necklace5_s6kth4.png",
    description: "This is Necklace.",
    rating: 2,
    inStock: 10,
    karat: 950,
    originalPrice: 70000,
  }
];
