const LOW_TO_HIGH = "LOW_TO_HIGH"
const HIGH_TO_LOW = "HIGH_TO_LOW"
const ON_SUCCESS = "ON_SUCCESS"
const GET_CATEGORY = "GET_CATEGORY"
const STAR_RATING = "STAR_RATING"
const PRICE_RANGE = "PRICE_RANGE"
const CLEAR_FILTER = "CLEAR_FILTER"
const FEATURED_PRODUCT = "FEATURED_PRODUCT"
const TOTAL_CART_ITEMS = "TOTAL_CART_ITEMS"
const ADD_TO_CART = "ADD_TO_CART"

export {FEATURED_PRODUCT ,LOW_TO_HIGH, HIGH_TO_LOW, ON_SUCCESS, GET_CATEGORY, STAR_RATING, PRICE_RANGE, CLEAR_FILTER, TOTAL_CART_ITEMS, ADD_TO_CART}