 const LOW_TO_HIGH = "LOW_TO_HIGH"
 const HIGH_TO_LOW = "HIGH_TO_LOW"
 const ON_SUCCESS = "ON_SUCCESS"
 const GET_CATEGORY = "GET_CATEGORY"
 const STAR_RATING = "STAR_RATING"
 const PRICE_RANGE = "PRICE_RANGE"
 const CLEAR_FILTER = "CLEAR_FILTER"
 const FEATURED_PRODUCT = "FEATURED_PRODUCT"
 const TOTAL_CART_ITEMS = "TOTAL_CART_ITEMS"
 const ADD_TO_CART = "ADD_TO_CART"
 const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
 const GET_CART_FROM_LOCAL_STORAGE = "GET_CART_FROM_LOCAL_STORAGE"
 const DELETE_PRODUCT = "DELETE_PRODUCT"
 const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"
 const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
 const INCREMENT_DECREMENT_QUANTITY = "INCREMENT_DECREMENT_QUANTITY"
 const SET_LOADER = "SET_LOADER";

 
export {SET_LOADER,INCREMENT_DECREMENT_QUANTITY,  DECREMENT_QUANTITY, INCREMENT_QUANTITY,  DELETE_PRODUCT, GET_CART_FROM_LOCAL_STORAGE, ADD_TO_WISHLIST,FEATURED_PRODUCT ,LOW_TO_HIGH, HIGH_TO_LOW, ON_SUCCESS, GET_CATEGORY, STAR_RATING, PRICE_RANGE, CLEAR_FILTER, TOTAL_CART_ITEMS, ADD_TO_CART}